// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bitoOA/internal/config"
	"bitoOA/internal/db"
	"bitoOA/internal/logger"
	"bitoOA/internal/route/handler"
	"bitoOA/internal/user"
)

import (
	_ "bitoOA/docs"
)

// Injectors from wire.go:

func InitializeApp() *App {
	configConfig := config.New()
	loggerLogger := logger.New(configConfig)
	service := db.New(loggerLogger)
	userService := user.New(service, loggerLogger)
	userController := handler.New(userService, loggerLogger)
	app := NewApp(userController, configConfig)
	return app
}
